## 2.2.1 创建 Tensor

导入 tensorflow, 并查看其版本信息。

In [1]:
import tensorflow as tf 
print(tf.__version__)

2.0.0


使用 tf.range() 函数创建一个张量，其作用类似于np.arange()，第一个数字表示开始的位置，第二个表示截至位置，第三个数字表示步长。

In [2]:
x = tf.range(0, 12, 1)
x 

<tf.Tensor: id=3, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

通过 shape 属性参考该张量的形状 

In [3]:
x.shape 

TensorShape([12])

可以通过len()函数查看张量中的元素总数 

In [5]:
len(x)

12

下面使用reshape函数把张量x的形状改为(3, 4)，也就是一个3行4列的矩阵，并记作X。除了形状改变之外，X中的元素保持不变。

In [10]:
X = tf.reshape(x, [3,4])
X

<tf.Tensor: id=5, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

注意X属性中的形状发生了变化。上面tf.reshape(x,[3,4])也可写成tf.reshape(x, [-1, 4])或tf.reshape(x, [3, -1])。由于x的元素个数是已知的，这里的 -1 是能够通过元素个数和其他维度的大小推断出来的。

接下来，我们创建一个各元素为0，形状为[2, 3, 4]的张量。实际上，之前创建的向量和矩阵都是特殊的张量。

In [16]:
tf.zeros([2,3,4])

<tf.Tensor: id=13, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

类似地，我们可以创建各元素为1的张量。

In [17]:
tf.ones([3,4])

<tf.Tensor: id=16, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

我们也可以通过Python的列表（list）指定需要创建的 tensor 中每个元素的值即将Python的列表转换为 tensor。

In [21]:
Y = tf.convert_to_tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y 

<tf.Tensor: id=18, shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

有些情况下，我们需要随机生成NDArray中每个元素的值。下面我们创建一个形状为[3, 4]的NDArray。它的每个元素都随机采样于均值为0、标准差为1的正态分布。

In [23]:
tf.random.normal(shape=[3,4], mean=0, stddev=1.0)

<tf.Tensor: id=24, shape=(3, 4), dtype=float32, numpy=
array([[ 0.16944583, -2.2878458 , -0.1884453 , -0.8675371 ],
       [ 0.01899109, -0.522431  ,  0.64564985, -0.6211288 ],
       [ 1.4195751 , -1.0959048 ,  1.6110578 , -0.79872185]],
      dtype=float32)>

## 2.2.2 运算

Tensor 支持大量的运算符(operator)。 

In [25]:
# 按元素加法
X + Y

<tf.Tensor: id=26, shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]])>

In [26]:
# 按元素乘法
X * Y

<tf.Tensor: id=27, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]])>

In [27]:
# 按元素除法
X / Y

<tf.Tensor: id=30, shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

In [37]:
# 按元素做指数运算
Y = tf.cast(Y, tf.float32) # 需要先把 Y 转换成 tf.float32 的格式
tf.math.exp(Y) 

<tf.Tensor: id=41, shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 54.598152 , 20.085537 ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.598152 ],
       [54.598152 , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

除了按元素计算外，我们还可以使用dot函数做矩阵乘法。可以使用 tf.transpose()对矩阵进行转置。 

In [39]:
Y = tf.cast(Y, dtype=tf.int32) #把 Y 转回整数型
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: id=46, shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]])>

我们也可以将多个Tensor 连结（concatenate）。下面分别在行上（维度0，即形状中的最左边元素）和列上（维度1，即形状中左起第二个元素）连结两个矩阵。

In [40]:
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: id=48, shape=(6, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])>,
 <tf.Tensor: id=50, shape=(3, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])>)

使用条件判断式可以得到元素为0或1的新的Tensor。以X == Y为例，如果X和Y在相同位置的条件判断为真（值相等），那么新的Tensor在相同位置的值为1；反之为0。

In [41]:
X == Y

<tf.Tensor: id=51, shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

对 Tensor 中所有元素求和得到只有一个元素的 Tensor 

In [43]:
tf.reduce_sum(X)

<tf.Tensor: id=53, shape=(), dtype=int32, numpy=66>

In [48]:
import numpy as np

X = tf.cast(X, tf.float32)
np.array(tf.norm(X))

array(22.494444, dtype=float32)