## 2.2.1 创建 Tensor

导入 tensorflow, 并查看其版本信息。

In [1]:
import tensorflow as tf 
print(tf.__version__)

2.0.0


使用 tf.range() 函数创建一个张量，其作用类似于np.arange()，第一个数字表示开始的位置，第二个表示截至位置，第三个数字表示步长。

In [2]:
x = tf.range(0, 12, 1)
x 

<tf.Tensor: id=3, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

通过 shape 属性参考该张量的形状 

In [3]:
x.shape 

TensorShape([12])

可以通过len()函数查看张量中的元素总数 

In [4]:
len(x)

12

下面使用reshape函数把张量x的形状改为(3, 4)，也就是一个3行4列的矩阵，并记作X。除了形状改变之外，X中的元素保持不变。

In [5]:
X = tf.reshape(x, [3,4])
X

<tf.Tensor: id=5, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

注意X属性中的形状发生了变化。上面tf.reshape(x,[3,4])也可写成tf.reshape(x, [-1, 4])或tf.reshape(x, [3, -1])。由于x的元素个数是已知的，这里的 -1 是能够通过元素个数和其他维度的大小推断出来的。

接下来，我们创建一个各元素为0，形状为[2, 3, 4]的张量。实际上，之前创建的向量和矩阵都是特殊的张量。

In [6]:
tf.zeros([2,3,4])

<tf.Tensor: id=8, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

类似地，我们可以创建各元素为1的张量。

In [7]:
tf.ones([3,4])

<tf.Tensor: id=11, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

我们也可以通过Python的列表（list）指定需要创建的 tensor 中每个元素的值即将Python的列表转换为 tensor。

In [8]:
Y = tf.convert_to_tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y 

<tf.Tensor: id=12, shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

有些情况下，我们需要随机生成NDArray中每个元素的值。下面我们创建一个形状为[3, 4]的NDArray。它的每个元素都随机采样于均值为0、标准差为1的正态分布。

In [9]:
tf.random.normal(shape=[3,4], mean=0, stddev=1.0)

<tf.Tensor: id=18, shape=(3, 4), dtype=float32, numpy=
array([[-0.1641506 , -1.987194  , -0.25492546,  0.42416218],
       [ 1.0759839 ,  1.7719746 ,  0.8112962 ,  0.65078896],
       [ 0.40286028,  0.9665915 ,  0.8804478 ,  1.8316692 ]],
      dtype=float32)>

## 2.2.2 运算

Tensor 支持大量的运算符(operator)。 

In [10]:
# 按元素加法
X + Y

<tf.Tensor: id=19, shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]])>

In [11]:
# 按元素乘法
X * Y

<tf.Tensor: id=20, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]])>

In [12]:
# 按元素除法
X / Y

<tf.Tensor: id=23, shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

In [13]:
# 按元素做指数运算
Y = tf.cast(Y, tf.float32) # 需要先把 Y 转换成 tf.float32 的格式
tf.math.exp(Y) 

<tf.Tensor: id=25, shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 54.598152 , 20.085537 ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.598152 ],
       [54.598152 , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

除了按元素计算外，我们还可以使用dot函数做矩阵乘法。可以使用 tf.transpose()对矩阵进行转置。 

In [14]:
Y = tf.cast(Y, dtype=tf.int32) #把 Y 转回整数型
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: id=29, shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]])>

我们也可以将多个Tensor 连结（concatenate）。下面分别在行上（维度0，即形状中的最左边元素）和列上（维度1，即形状中左起第二个元素）连结两个矩阵。

In [15]:
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: id=31, shape=(6, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])>,
 <tf.Tensor: id=33, shape=(3, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])>)

使用条件判断式可以得到元素为0或1的新的Tensor。以X == Y为例，如果X和Y在相同位置的条件判断为真（值相等），那么新的Tensor在相同位置的值为1；反之为0。

In [16]:
X == Y

<tf.Tensor: id=34, shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

对 Tensor 中所有元素求和得到只有一个元素的 Tensor 

In [17]:
tf.reduce_sum(X)

<tf.Tensor: id=36, shape=(), dtype=int32, numpy=66>

使用 np.array()将 Tensor转化成 Numpy 的array格式。 下面例子中 X 的 L2 范数结果同上例一样是单元素Tensor。

In [18]:
import numpy as np

X = tf.cast(X, tf.float32)
np.array(tf.norm(X))

array(22.494444, dtype=float32)

## 2.2.3. 广播机制
前面我们看到如何对两个形状相同的Tensor做按元素运算。当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。

In [19]:
A = tf.reshape(tf.range(0,3,1), [3,1])
B = tf.reshape(tf.range(0,2,1), [1,2])
A,B

(<tf.Tensor: id=48, shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: id=54, shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

由于A和B分别是3行1列和1行2列的矩阵，如果要计算A + B，那么A中第一列的3个元素被广播（复制）到了第二列，而B中第一行的2个元素被广播（复制）到了第二行和第三行。如此，就可以对2个3行2列的矩阵按元素相加。

In [20]:
A + B 

<tf.Tensor: id=55, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

## 2.2.4. 索引
在Tensor中，索引（index）代表了元素的位置。Tensor的索引从0开始逐一递增。例如，一个3行2列的矩阵的行索引分别为0、1和2，列索引分别为0和1。

In [21]:
X[1:3]

<tf.Tensor: id=59, shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

为某个特定位置的元素重新赋值，需要先将 Tensor 变成 Variable，再使用 assign 赋值

In [22]:
X = tf.Variable(X)
X[1,2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## 2.2.5. 运算的内存开销
在前面的例子里我们对每个操作新开内存来存储运算结果。举个例子，即使像Y = X + Y这样的运算，我们也会新开内存，然后将Y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [23]:
X = tf.cast(X, tf.int32)  # 要先把 X 的格式转换成 tf.int32

In [24]:
before = id(Y)
Y = Y + X
id(Y) == before

False

在下面的例子中，我们先通过zeros_like创建和Y形状相同且元素为0的Tensor，记为Z。接下来，我们把X + Y的结果通过[:]写进Z对应的内存中。此时内存地址仍然有改变（暂时没有找到不改变内存地址的方法，有朋友有发现请告知）。

In [25]:
Z = tf.zeros_like(Y)
before = id(Z)
Z = tf.Variable(Z)
Z[:].assign(X + Y)
id(Z) == before 

False

## 2.2.6. Tensor 和 NumPy相互变换

我们可以通过numpy()函数和convert_to_tensor()函数令数据在Tensor和NumPy格式之间相互变换。

In [26]:
p = np.ones((2,3))
D = tf.convert_to_tensor(p)
D 

<tf.Tensor: id=90, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

再将Tensor实例变换成NumPy实例。

In [27]:
D.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])